"use client"
import './globals.css'
import Providers from './providers'
import ThemeSwitcher from './ThemeSwitcher'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Hot News',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <ThemeSwitcher />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
